version: 2
build:
    os: ubuntu-lts-latest
    tools:
        python: mambaforge-latest
    jobs:
        pre_install:
          - git update-index --assume-unchanged environment.yaml docs/conf.py
        pre_build:
          - git status
conda:
    environment: environment.yaml
sphinx:
    configuration: docs/conf.py
