name: production
on:
    push:
        tags:
          - "v*.*.*"
    workflow_dispatch:
jobs:
    publish-package:
        runs-on: ubuntu-latest
        environment: production
        steps:
          - name: setup-python
            uses: actions/setup-python@v5
            with:
                python-version: "3.10"
          - name: checkout-branch
            uses: actions/checkout@v4
          - name: install-package
            run: pip install -e .[development]
          - name: build-package
            run: python -m build
          - name: publish-package
            env:
                TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
                TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
            run: twine upload dist/*
